const DAY=86400000;
const EVENTS=[
{d:0,t:"hero",k:"initial",i:["Natalia","Molly","Patrick","Sergey","Jessie"]},
{d:14,t:"map",k:"tundra",i:["Tundra"]},
{d:34,t:"arena",k:"arena",i:["Nearby State pool"]},
{d:39,t:"map",k:"fertile",i:["Fertile Land"]},
{d:40,t:"hero",k:"gen2",i:["Alonso","Flint","Philly"]},
{d:53,t:"castle",k:"castle",i:["Sunfire Castle","President","Ministers"]},
{d:54,t:"pet",k:"pets1",i:["Musk Ox","Arctic Wolf","Cave Hyena"]},
{d:60,t:"crystal",k:"fc13",i:["Fire Crystal 1","Fire Crystal 2","Fire Crystal 3"]},
{d:80,t:"battle",k:"svs",i:["State of Power","King of Icefield"]},
{d:90,t:"pet",k:"pets2",i:["Titan Roc","Giant Tapir"]},
{d:120,t:"hero",k:"gen3",i:["Greg","Logan","Mia"]},
{d:140,t:"pet",k:"pets3",i:["Giant Elk","Snow Leopard"]},
{d:150,t:"crystal",k:"fc45",i:["Fire Crystal 4","Fire Crystal 5","Crystal Laboratory"]},
{d:180,t:"gear",k:"legendary",i:["Legendary Chief Gear"]},
{d:195,t:"hero",k:"gen4",i:["Ahmose","Lynn","Reina"]},
{d:200,t:"pet",k:"pets4",i:["Snow Ape","Cave Lion"]},
{d:220,t:"academy",k:"academy",i:["War Academy","Fire Crystal Shard","Infantry T11","Lancer T11","Marksman T11"]},
{d:270,t:"hero",k:"gen5",i:["Gwen","Hector","Norah"]},
{d:280,t:"pet",k:"pets5",i:["Iron Rhino","Saber-tooth Tiger"]},
{d:315,t:"crystal",k:"fc68",i:["Fire Crystal 6–8","Refined Fire Crystal"]},
{d:360,t:"hero",k:"gen6",i:["Renee","Wayne","Wuming"]},
{d:370,t:"pet",k:"mammoth",i:["Mammoth"]},
{d:440,t:"hero",k:"gen7",i:["Bradley","Edith","Gordon"]},
{d:500,t:"crystal",k:"fc910",i:["Fire Crystal 9","Fire Crystal 10"]},
{d:520,t:"hero",k:"gen8",i:["Gatot","Hendrik","Sonya"]},
{d:600,t:"hero",k:"gen9",i:["Fred","Magnus","Xura"]},
{d:700,t:"hero",k:"gen10",i:["Blanchette","Freya","Gregory"]},
{d:800,t:"hero",k:"gen11",i:["Eleonora Gold","Lloyd","Rufus"]},
{d:870,t:"hero",k:"gen12",i:["Ligeia","Karol","Hervor"]},
{d:951,t:"hero",k:"gen13",i:["Gisela","Flora","Vulcanus"]},
{d:1000,t:"unknown",k:"gen14",i:["Unconfirmed content"]}
];
const EN={initial:"Initial Heroes",tundra:"Tundra",arena:"Arena Opponent Update",fertile:"Fertile Land",gen2:"Gen 2 Heroes",castle:"Sunfire Castle",pets1:"First Pets Update",fc13:"Fire Crystal Age",svs:"SvS & King of Icefield",pets2:"Second Pets Update",gen3:"Gen 3 Heroes",pets3:"Third Pets Update",fc45:"Crystal Infrastructure",legendary:"Legendary Equipment",gen4:"Gen 4 Heroes",pets4:"Fourth Pets Update",academy:"War Academy & T11",gen5:"Gen 5 Heroes",pets5:"Fifth Pets Update",fc68:"Advanced Crystal Update",gen6:"Gen 6 Heroes",mammoth:"Mammoth Update",gen7:"Gen 7 Heroes",fc910:"Crystal Mastery",gen8:"Gen 8 Heroes",gen9:"Gen 9 Heroes",gen10:"Gen 10 Heroes",gen11:"Gen 11 Heroes",gen12:"Gen 12 Heroes",gen13:"Gen 13 Heroes",gen14:"Unconfirmed Gen 14"};
const ZHT={initial:"初始英雄",tundra:"凍土開放",arena:"競技場對手更新",fertile:"肥沃之地",gen2:"第二代英雄",castle:"王城爭奪戰",pets1:"第一批寵物",fc13:"火晶時代",svs:"SvS／凍土之王",pets2:"第二批寵物",gen3:"第三代英雄",pets3:"第三批寵物",fc45:"火晶基礎建設",legendary:"傳說領主裝備",gen4:"第四代英雄",pets4:"第四批寵物",academy:"戰爭學院／T11",gen5:"第五代英雄",pets5:"第五批寵物",fc68:"高階火晶更新",gen6:"第六代英雄",mammoth:"猛獁象更新",gen7:"第七代英雄",fc910:"火晶精通",gen8:"第八代英雄",gen9:"第九代英雄",gen10:"第十代英雄",gen11:"第十一代英雄",gen12:"第十二代英雄",gen13:"第十三代英雄",gen14:"尚未確認的第十四代"};
const ZHS={...ZHT,initial:"初始英雄",tundra:"冻土开放",arena:"竞技场对手更新",fertile:"肥沃之地",gen2:"第二代英雄",castle:"王城争夺战",pets1:"第一批宠物",fc13:"火晶时代",svs:"SvS／冻土之王",pets2:"第二批宠物",gen3:"第三代英雄",pets3:"第三批宠物",fc45:"火晶基础建设",legendary:"传说领主装备",gen4:"第四代英雄",pets4:"第四批宠物",academy:"战争学院／T11",gen5:"第五代英雄",pets5:"第五批宠物",fc68:"高阶火晶更新",gen6:"第六代英雄",mammoth:"猛犸象更新",gen7:"第七代英雄",fc910:"火晶精通",gen8:"第八代英雄",gen9:"第九代英雄",gen10:"第十代英雄",gen11:"第十一代英雄",gen12:"第十二代英雄",gen13:"第十三代英雄",gen14:"尚未确认的第十四代"};
const ES={initial:"Héroes iniciales",tundra:"Tundra",arena:"Actualización de rivales de Arena",fertile:"Tierra fértil",gen2:"Héroes Gen 2",castle:"Castillo Sunfire",pets1:"Primera generación de mascotas",fc13:"Era del Cristal de Fuego",svs:"SvS y Rey del Campo de Hielo",pets2:"Segunda generación de mascotas",gen3:"Héroes Gen 3",pets3:"Tercera generación de mascotas",fc45:"Infraestructura de Cristal",legendary:"Equipo legendario",gen4:"Héroes Gen 4",pets4:"Cuarta generación de mascotas",academy:"Academia de Guerra y T11",gen5:"Héroes Gen 5",pets5:"Quinta generación de mascotas",fc68:"Cristal avanzado",gen6:"Héroes Gen 6",mammoth:"Mamut",gen7:"Héroes Gen 7",fc910:"Maestría de Cristal",gen8:"Héroes Gen 8",gen9:"Héroes Gen 9",gen10:"Héroes Gen 10",gen11:"Héroes Gen 11",gen12:"Héroes Gen 12",gen13:"Héroes Gen 13",gen14:"Gen 14 sin confirmar"};
const EVENT_NAMES={"zh-TW":ZHT,"zh-CN":ZHS,en:EN,es:ES};
const T={
"zh-TW":{brand:"寒霜工具站",live:"即時資料庫",navTracker:"State 追蹤",navHighlights:"進度摘要",navTimeline:"解鎖時間軸",navData:"State 資料庫",sideNote:"獨立玩家工具，清楚標示每筆資料的精度。",kicker:"STATE 時間軸工具",title:"寒霜啟示錄<br><em>State 年齡追蹤器</em>",intro:"輸入 State 編號，查看精確開服時間、伺服器年齡、已解鎖內容與接下來的完整進度。",creation:"開服時間",unlocks:"即時解鎖",visual:"視覺時間軸",stateLabel:"STATE 編號",search:"查詢 State",lookup:"本站資料庫即時查詢",creationK:"STATE 開服日期與時間",creationEmpty:"搜尋 State 以顯示開服時間",creationSub:"精確時間以 UTC 顯示；只有日期的紀錄會清楚標示。",verified:"已驗證資料庫",recent:"最近收錄的 States",records:"{n} 筆紀錄",dbUpdated:"資料庫更新：{date}",manualK:"手動 UTC 備援",manualTitle:"資料庫尚未收錄",manualText:"可輸入 UTC 日期與時間；資料只保存在這部裝置。",save:"使用手動時間",latest:"最新已解鎖",next:"下一個重大解鎖",progress:"STATE 進度",currentDay:"目前天數",unlocked:"已解鎖",upcoming:"未解鎖",milestones:"里程碑",source:"資料來源",updated:"更新日期",roadmap:"視覺 STATE 路線圖",timeline:"完整解鎖時間軸",timelineNote:"每張卡片包含常見開放日、內容明細與預估日期；實際時間可能因官方調整而不同。",locked:"未解鎖",exact:"精確 UTC",dateOnly:"僅日期",database:"本站資料庫",local:"本機手動資料",day:"Day {n}",daysLeft:"{n} 天後",today:"預計今天",opened:"已開放 {n} 天",expected:"預計 {date}",notFound:"找不到 State {state}",found:"已找到 State {state}",footer:"非官方玩家工具。時間軸為社群常見進度，不保證遊戲內實際開放時間。",descHero:"新一代英雄加入招募與活動輪替。",descMap:"State 地圖與領土進度開放新的區域。",descArena:"競技場配對池擴展到鄰近 States。",descCastle:"王城爭奪、總統與官職系統進入 State 進度。",descPet:"新的寵物與對應培養內容開放。",descCrystal:"火晶建築、等級或相關研究進一步開放。",descBattle:"跨 State 競賽與大型戰鬥進度開放。",descGear:"領主裝備開放新的品質與成長階段。",descAcademy:"戰爭學院、火晶科技與 T11 部隊開放。",descUnknown:"此階段仍待官方或玩家資料確認。"},
"zh-CN":{brand:"寒霜工具站",live:"实时数据库",navTracker:"State 追踪",navHighlights:"进度摘要",navTimeline:"解锁时间轴",navData:"State 数据库",sideNote:"独立玩家工具，清楚标示每笔资料的精度。",kicker:"STATE 时间轴工具",title:"寒霜启示录<br><em>State 年龄追踪器</em>",intro:"输入 State 编号，查看精确开服时间、服务器年龄、已解锁内容与接下来的完整进度。",creation:"开服时间",unlocks:"实时解锁",visual:"可视化时间轴",stateLabel:"STATE 编号",search:"查询 State",lookup:"本站数据库实时查询",creationK:"STATE 开服日期与时间",creationEmpty:"查询 State 以显示开服时间",creationSub:"精确时间以 UTC 显示；只有日期的记录会清楚标示。",verified:"已验证数据库",recent:"最近收录的 States",records:"{n} 条记录",dbUpdated:"数据库更新：{date}",manualK:"手动 UTC 备用",manualTitle:"数据库尚未收录",manualText:"可输入 UTC 日期与时间；资料只保存在此设备。",save:"使用手动时间",latest:"最新已解锁",next:"下一个重大解锁",progress:"STATE 进度",currentDay:"当前天数",unlocked:"已解锁",upcoming:"未解锁",milestones:"里程碑",source:"资料来源",updated:"更新日期",roadmap:"可视化 STATE 路线图",timeline:"完整解锁时间轴",timelineNote:"每张卡片包含常见开放日、内容明细和预计日期；实际时间可能因官方调整而不同。",locked:"未解锁",exact:"精确 UTC",dateOnly:"仅日期",database:"本站数据库",local:"本机手动资料",day:"Day {n}",daysLeft:"{n} 天后",today:"预计今天",opened:"已开放 {n} 天",expected:"预计 {date}",notFound:"找不到 State {state}",found:"已找到 State {state}",footer:"非官方玩家工具。时间轴为社群常见进度，不保证游戏内实际开放时间。",descHero:"新一代英雄加入招募与活动轮换。",descMap:"State 地图与领土进度开放新区域。",descArena:"竞技场匹配池扩展至邻近 States。",descCastle:"王城争夺、总统和官职系统进入 State 进度。",descPet:"新的宠物与相应培养内容开放。",descCrystal:"火晶建筑、等级或相关研究进一步开放。",descBattle:"跨 State 竞赛与大型战斗进度开放。",descGear:"领主装备开放新的品质与成长阶段。",descAcademy:"战争学院、火晶科技与 T11 部队开放。",descUnknown:"此阶段仍待官方或玩家资料确认。"},
en:{brand:"Frost State Tools",live:"Live database",navTracker:"State Tracker",navHighlights:"Highlights",navTimeline:"Unlock Timeline",navData:"State Database",sideNote:"Independent player tool with transparent data precision.",kicker:"STATE TIMELINE TOOL",title:"Whiteout Survival<br><em>State Age Tracker</em>",intro:"Enter a State number to see its opening time, age, live content, and every major unlock that comes next.",creation:"Creation time",unlocks:"Live unlocks",visual:"Visual timeline",stateLabel:"STATE NUMBER",search:"Check State",lookup:"Live database lookup",creationK:"STATE CREATION DATE & TIME",creationEmpty:"Search a State to reveal its opening time",creationSub:"Exact timestamps use UTC; date-only records are clearly marked.",verified:"VERIFIED DATABASE",recent:"Recently added States",records:"{n} records",dbUpdated:"Database updated: {date}",manualK:"MANUAL UTC FALLBACK",manualTitle:"State not in database",manualText:"Enter its UTC date and time. This remains on this device only.",save:"Use manual time",latest:"LATEST LIVE UNLOCK",next:"NEXT MAJOR UNLOCK",progress:"STATE PROGRESS",currentDay:"Current day",unlocked:"Unlocked",upcoming:"Upcoming",milestones:"Milestones",source:"Source",updated:"Updated",roadmap:"VISUAL STATE ROADMAP",timeline:"Complete unlock timeline",timelineNote:"Each card includes common timing, content details, and an estimated date. Official adjustments may differ.",locked:"Locked",exact:"Exact UTC",dateOnly:"Date only",database:"Site database",local:"Manual / local",day:"Day {n}",daysLeft:"in {n} days",today:"Expected today",opened:"Active for {n} days",expected:"Expected {date}",notFound:"State {state} is not in the database",found:"State {state} found",footer:"Unofficial player tool. Timeline timing is community guidance and is not guaranteed in game.",descHero:"A new hero generation enters recruitment and event rotations.",descMap:"New territory opens as the State map progresses.",descArena:"The Arena opponent pool expands to nearby States.",descCastle:"Castle battle, presidency, and minister appointments enter State play.",descPet:"New pets and their development content become available.",descCrystal:"Fire Crystal buildings, levels, or research advance.",descBattle:"Cross-State competition and major battle content become available.",descGear:"Chief Gear reaches a new quality and progression stage.",descAcademy:"War Academy, Fire Crystal technology, and T11 troops unlock.",descUnknown:"This stage still needs official or community confirmation."},
es:{brand:"Herramientas Frost",live:"Base de datos en vivo",navTracker:"Rastreador",navHighlights:"Resumen",navTimeline:"Cronología",navData:"Base de datos",sideNote:"Herramienta independiente con precisión de datos transparente.",kicker:"CRONOLOGÍA DE ESTADO",title:"Whiteout Survival<br><em>Rastreador de antigüedad</em>",intro:"Introduce un Estado para ver su apertura, antigüedad, contenido activo y todos los desbloqueos importantes.",creation:"Hora de creación",unlocks:"Desbloqueos",visual:"Cronología visual",stateLabel:"NÚMERO DE ESTADO",search:"Buscar Estado",lookup:"Consulta en nuestra base de datos",creationK:"FECHA Y HORA DE CREACIÓN",creationEmpty:"Busca un Estado para ver su apertura",creationSub:"Las horas exactas usan UTC; los registros sin hora están marcados.",verified:"BASE VERIFICADA",recent:"Estados añadidos recientemente",records:"{n} registros",dbUpdated:"Base actualizada: {date}",manualK:"ENTRADA UTC MANUAL",manualTitle:"Estado no registrado",manualText:"Introduce fecha y hora UTC. Solo se guarda en este dispositivo.",save:"Usar hora manual",latest:"ÚLTIMO DESBLOQUEO",next:"PRÓXIMO DESBLOQUEO",progress:"PROGRESO DEL ESTADO",currentDay:"Día actual",unlocked:"Desbloqueado",upcoming:"Próximos",milestones:"Hitos",source:"Fuente",updated:"Actualizado",roadmap:"RUTA VISUAL DEL ESTADO",timeline:"Cronología completa",timelineNote:"Cada tarjeta incluye tiempo habitual, detalles y fecha estimada. Los ajustes oficiales pueden variar.",locked:"Bloqueado",exact:"UTC exacta",dateOnly:"Solo fecha",database:"Base del sitio",local:"Manual / local",day:"Día {n}",daysLeft:"en {n} días",today:"Previsto hoy",opened:"Activo durante {n} días",expected:"Previsto {date}",notFound:"El Estado {state} no está registrado",found:"Estado {state} encontrado",footer:"Herramienta no oficial. La cronología es una guía comunitaria y no se garantiza en el juego.",descHero:"Una nueva generación de héroes entra en reclutamiento y eventos.",descMap:"Se abre nuevo territorio con el progreso del Estado.",descArena:"La Arena amplía sus rivales a Estados cercanos.",descCastle:"La batalla del Castillo, presidencia y ministros entran en juego.",descPet:"Se habilitan nuevas mascotas y su desarrollo.",descCrystal:"Avanzan edificios, niveles o investigaciones de Cristal de Fuego.",descBattle:"Se habilitan competiciones entre Estados y grandes batallas.",descGear:"El equipo del Jefe alcanza una nueva etapa de calidad.",descAcademy:"Se desbloquean Academia, tecnología de Cristal y tropas T11.",descUnknown:"Esta etapa aún necesita confirmación oficial o comunitaria."}
};
const PARTIAL={ja:{brand:"フロストツール",live:"ライブデータ",navTracker:"State検索",navHighlights:"進行状況",navTimeline:"解放タイムライン",navData:"データベース",search:"Stateを確認",currentDay:"現在の日数",unlocked:"解放済み",upcoming:"未解放",milestones:"マイルストーン",locked:"未解放",exact:"正確なUTC",dateOnly:"日付のみ",day:"{n}日目",daysLeft:"あと{n}日"},ko:{brand:"프로스트 도구",live:"실시간 데이터",navTracker:"State 검색",navHighlights:"진행 요약",navTimeline:"해금 일정",navData:"데이터베이스",search:"State 확인",currentDay:"현재 일차",unlocked:"해금",upcoming:"예정",milestones:"단계",locked:"잠김",exact:"정확한 UTC",dateOnly:"날짜만",day:"{n}일차",daysLeft:"{n}일 후"},th:{brand:"เครื่องมือ Frost",live:"ฐานข้อมูลสด",navTracker:"ค้นหา State",navHighlights:"สรุป",navTimeline:"ไทม์ไลน์",navData:"ฐานข้อมูล",search:"ตรวจสอบ State",currentDay:"วันที่ปัจจุบัน",unlocked:"ปลดล็อกแล้ว",upcoming:"กำลังมา",milestones:"เหตุการณ์",locked:"ยังล็อก",exact:"UTC แม่นยำ",dateOnly:"เฉพาะวันที่",day:"วันที่ {n}",daysLeft:"อีก {n} วัน"},vi:{brand:"Công cụ Frost",live:"Dữ liệu trực tiếp",navTracker:"Tìm State",navHighlights:"Tóm tắt",navTimeline:"Lộ trình",navData:"Cơ sở dữ liệu",search:"Kiểm tra State",currentDay:"Ngày hiện tại",unlocked:"Đã mở",upcoming:"Sắp tới",milestones:"Cột mốc",locked:"Chưa mở",exact:"UTC chính xác",dateOnly:"Chỉ ngày",day:"Ngày {n}",daysLeft:"còn {n} ngày"},id:{brand:"Frost Tools",live:"Database langsung",navTracker:"Cari State",navHighlights:"Ringkasan",navTimeline:"Linimasa",navData:"Database",search:"Periksa State",currentDay:"Hari saat ini",unlocked:"Terbuka",upcoming:"Akan datang",milestones:"Tonggak",locked:"Terkunci",exact:"UTC tepat",dateOnly:"Tanggal saja",day:"Hari {n}",daysLeft:"{n} hari lagi"}};
for(const [code,part] of Object.entries(PARTIAL))T[code]={...T.en,...part};
let language=localStorage.getItem("wosLang")||((navigator.language||"").startsWith("zh-CN")?"zh-CN":T[navigator.language]?navigator.language:"zh-TW");
let database=null,current=null;
const $=id=>document.getElementById(id);
const tr=(key,data={})=>Object.entries(data).reduce((s,[k,v])=>s.replaceAll(`{${k}}`,v),T[language]?.[key]||T.en[key]||key);
const name=e=>(EVENT_NAMES[language]||EN)[e.k]||EN[e.k];
const desc=e=>tr({hero:"descHero",map:"descMap",arena:"descArena",castle:"descCastle",pet:"descPet",crystal:"descCrystal",battle:"descBattle",gear:"descGear",academy:"descAcademy",unknown:"descUnknown"}[e.t]);
const fmt=(date,time=false)=>new Intl.DateTimeFormat(language,{timeZone:"UTC",year:"numeric",month:"short",day:"numeric",...(time?{hour:"2-digit",minute:"2-digit",hourCycle:"h23"}:{})}).format(date)+(time?" UTC":"");
const manualStates=()=>{try{return JSON.parse(localStorage.getItem("manualStates")||"{}")}catch{return {}}};
const ageOf=date=>Math.max(0,Math.floor((Date.now()-date.getTime())/DAY));
async function getDatabase(){if(database)return database;try{const r=await fetch(`./states.json?v=${Date.now()}`);if(!r.ok)throw 0;database=await r.json()}catch{database={_meta:{},states:{}}}renderRecent();return database}
function renderRecent(){if(!database)return;const rows=Object.entries(database.states||{}).filter(([,r])=>r.opened_utc).sort((a,b)=>new Date(b[1].opened_utc)-new Date(a[1].opened_utc)).slice(0,5);$("recordCount").textContent=tr("records",{n:Object.keys(database.states||{}).length});$("recentMeta").textContent=tr("dbUpdated",{date:database._meta?.updated_utc||"—"});$("recentList").innerHTML=rows.map(([s,r])=>`<div class="recent-state"><strong>#${s}</strong><span>${fmt(new Date(r.opened_utc))} · ${r.precision==="exact"?tr("exact"):tr("dateOnly")}</span></div>`).join("")}
function renderTimeline(age=null,opened=null){let nextSeen=false;$("timeline").innerHTML=EVENTS.map((e,i)=>{const done=age!==null&&age>=e.d,next=age!==null&&!done&&!nextSeen;if(next)nextSeen=true;const status=done?tr("unlocked"):next?(Math.max(0,e.d-age)?tr("daysLeft",{n:Math.max(0,e.d-age)}):tr("today")):tr("locked");const date=opened?fmt(new Date(opened.getTime()+e.d*DAY)):"";return `<article class="event-card ${done?"done":next?"next":""}"><span class="event-no">${String(i+1).padStart(2,"0")}</span><div class="event-top"><span class="event-day">${tr("day",{n:e.d})}</span><span class="event-status">${status}</span></div><h3>${name(e)}</h3><p>${desc(e)}</p><div class="chips">${e.i.map(x=>`<span>${x}</span>`).join("")}</div>${date?`<small class="event-date">${tr("expected",{date})}</small>`:""}</article>`}).join("")}
function applyLanguage(){document.documentElement.lang=language;$("lang").value=language;const map={live:"liveLabel",navTracker:"navTracker",navHighlights:"navHighlights",navTimeline:"navTimeline",navData:"navData",sideNote:"sideNote",kicker:"kicker",intro:"intro",creation:"pillCreation",unlocks:"pillUnlocks",visual:"pillTimeline",stateLabel:"stateLabel",lookup:"searchMode",creationK:"creationK",creationSub:"creationSub",verified:"recentK",recent:"recentTitle",manualK:"manualK",manualTitle:"manualTitle",manualText:"manualText",save:"saveBtn",latest:"latestK",progress:"summaryK",currentDay:"ageK",upcoming:"upcomingK",milestones:"totalK",source:"sourceK",updated:"updatedK",roadmap:"timelineK",timeline:"timelineTitle",timelineNote:"timelineNote",locked:"legendLocked",footer:"footer"};for(const [k,id] of Object.entries(map))if($(id))$(id).textContent=tr(k);for(const id of ["brand","footerBrand"])$(id).textContent=tr("brand");for(const id of ["unlockedK","legendDone"])$(id).textContent=tr("unlocked");for(const id of ["nextK","legendNext"])$(id).textContent=tr("next");$("title").innerHTML=tr("title");$("searchBtn").querySelector("span").textContent=tr("search");if(!current)$("creationV").textContent=tr("creationEmpty");renderRecent();current?showResult(current.state,current.date,current.record,current.local):renderTimeline()}
function showResult(state,date,record={},local=false){const age=ageOf(date),done=EVENTS.filter(e=>age>=e.d),next=EVENTS.find(e=>age<e.d);current={state,date,record,local};$("manual").classList.add("hidden");$("highlights").classList.remove("hidden");$("summary").classList.remove("hidden");$("creationV").textContent=(record.precision==="exact"||local?fmt(date,true):fmt(date))+` · ${tr("opened",{n:age})}`;$("latestV").textContent=name(done.at(-1)||EVENTS[0]);$("latestSub").textContent=tr("day",{n:(done.at(-1)||EVENTS[0]).d});$("nextV").textContent=next?name(next):tr("unlocked");$("nextSub").textContent=next?`${tr("day",{n:next.d})} · ${tr("daysLeft",{n:next.d-age})}`:tr("unlocked");$("summaryTitle").textContent=`State #${state}`;$("precisionBadge").textContent=local?tr("local"):(record.precision==="exact"?tr("exact"):tr("dateOnly"));$("ageV").textContent=tr("day",{n:age});$("unlockedV").textContent=done.length;$("upcomingV").textContent=EVENTS.length-done.length;$("progressBar").style.width=`${Math.min(100,age/EVENTS.at(-1).d*100)}%`;$("sourceV").textContent=local?tr("local"):(record.source?new URL(record.source).hostname:tr("database"));$("updatedV").textContent=local?"—":record.updated_utc||database?._meta?.updated_utc||"—";renderTimeline(age,date)}
async function lookup(){const state=$("state").value.trim();if(!/^\d{1,5}$/.test(state))return;history.replaceState(null,"",`${location.pathname}?state=${encodeURIComponent(state)}`);const db=await getDatabase(),record=db.states?.[state],saved=manualStates()[state];if(record?.opened_utc)showResult(state,new Date(record.opened_utc),record,false);else if(saved)showResult(state,new Date(saved),{precision:"exact"},true);else{current=null;$("creationV").textContent=tr("notFound",{state});$("manual").classList.remove("hidden");$("highlights").classList.add("hidden");$("summary").classList.add("hidden");renderTimeline()}}
$("searchBtn").onclick=lookup;$("state").addEventListener("keydown",e=>{if(e.key==="Enter")lookup()});$("saveBtn").onclick=()=>{const s=$("state").value.trim(),d=$("date").value,t=$("time").value||"00:00";if(!s||!d)return;const date=new Date(`${d}T${t}:00Z`),saved=manualStates();saved[s]=date.toISOString();localStorage.setItem("manualStates",JSON.stringify(saved));showResult(s,date,{precision:"exact"},true)};$("lang").onchange=e=>{language=e.target.value;localStorage.setItem("wosLang",language);applyLanguage()};
applyLanguage();getDatabase().then(()=>{const q=new URLSearchParams(location.search).get("state");if(q){$("state").value=q;lookup()}});
